apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: frontend 
labels: 
app: frontend 
spec: 
 replicas: 1
 selector: 
   matchLabels:
    app: frontend 

 template: 
  metadata: 
   labels: 
    app: frontend
  spec: 
   containers:
   - name: frontend 
   image: karimaali/udagram-api-frontend:v1
   imagePullPolicy: Always
   resources: 
    requests: 
     memory: "128Mi"
     cpu: "250m"
     limits:
      memory: "1024Mi"
      cpu: "500m"
     envForm:
     -secretRef:
      name: env-secret
    -configMapRef:
      name: env-config
    -secretRef:
      name: aws-secret

   ports: 
   - containerPort: 8080